# Generated by Django 6.1.1 on 2026-10-09 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Passaporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_restaurante", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("historia", models.TextField()),
                ("impacto_comunitario", models.TextField(blank=True)),
                ("programa_fidelidade", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("nota_geral", models.FloatField()),
                ("pilares", models.JSONField(default=dict)),
                ("respostas", models.JSONField(default=list)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosticos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("origem", models.CharField(max_length=150)),
                ("fornecedor", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True)),
                (
                    "passaporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="guardiao.passaporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissaoPlano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("missao_id", models.CharField(max_length=50)),
                ("pilar", models.CharField(max_length=30)),
                ("semana", models.PositiveSmallIntegerField()),
                ("destacada", models.BooleanField(default=False)),
                ("concluida", models.BooleanField(default=False)),
                (
                    "diagnostico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missoes",
                        to="guardiao.diagnostico",
                    ),
                ),
            ],
            options={
                "ordering": ["semana"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("diagnostico", "missao_id"),
                        name="missao_unica_por_diagnostico",
                    )
                ],
            },
        ),
    ]
