# Generated by Django 6.1.1 on 2026-10-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('insumos', 'Insumos e ingredientes'), ('folha', 'Folha de pagamento'), ('aluguel', 'Aluguel'), ('energia', 'Energia'), ('agua', 'Água'), ('gas', 'Gás'), ('manutencao', 'Manutenção'), ('marketing', 'Marketing'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
